export const baseURL='https://www.saucedemo.com';
export const input_username='input[id="user-name"]';
export const input_password='input[id="password"]';
export const button_login='input[type="submit"]';
export const title_app='div[class="app_logo"]';
export const menu='button[id="react-burger-menu-btn"]';
export const logout='a[id="logout_sidebar_link"]';
export const back_to_products='button[id="back-to-products"]';
export const first_product='div[class="inventory_item_name "]:first';
export const add_to_cart='*[id="add-to-cart"]';
export const shopping_cart='*[id="shopping_cart_container"] a span';
